app/blogs/urls.py
from django.urls import path

from . import api, views

app_name = "blogs"

urlpatterns = [
    # post views
    path("", views.blog_ajax_list, name="blog_list"),
    path("new/", views.new_blog, name="new_blog"),
    path("edit/<slug:slug>", views.edit_blog, name="edit_blog"),
    path("delete/<int:blog_id>", views.delete_blog, name="delete_blog"),
    path("manage/", views.manage_blogs, name="manage_blogs"),
    path("follow/", views.blog_follow, name="blog_follow"),
    path("<slug:slug>/followers", views.blog_followers, name="blog_followers"),
    path("<slug:slug>/", views.blog_detail, name="blog_detail"),
    path("detailed", api.get_detailed_blogs, name="blog_detailed"),
]

app/posts/urls.py
from django.urls import path

from . import api, views

app_name = "posts"

urlpatterns = [
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("post/<int:blog_id>/create/", views.create_post, name="create_post"),
    path("post/<slug:post_slug>/edit/", views.edit_post, name="edit_post"),
    path("delete/<int:post_id>", views.delete_post, name="delete_post"),
    path("manage/<slug:blog_slug>", views.manage_posts, name="manage_posts"),
    path("", views.post_list, name="post_list"),
    path("detailed/", api.get_detailed_posts, name="post_detailed"),
]

app/publishing_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("blogs/", include("blogs.urls", namespace="blogs")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("search/", include("search.urls", namespace="search")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blogs/models.py
from django.db import models
from django.db.models.expressions import F
from django.urls import reverse

from account.models import Profile
from common.utils import unique_slugify
from tags.models import Tag

from .managers import BlogIsActiveManager, FollowRelationshipManager
from .utils import get_blog_image_dir_path


class Blog(models.Model):
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    about = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to=get_blog_image_dir_path, blank=True)

    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="blogs")

    followers = models.ManyToManyField(
        Profile,
        through="FollowRelationship",
        related_name="following",
        symmetrical=False,
    )

    tags = models.ManyToManyField(Tag, through="TaggedBlog")

    objects = models.Manager()
    active = BlogIsActiveManager()

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"{self.title} ({self.author.user.get_username()})"

    def get_absolute_url(self):
        return reverse("blogs:blog_detail", args=[self.slug])

    def get_new_followers(self):
        return FollowRelationship.objects.notseen(blog_id=self.id).annotate(
            old=F("seen")
        )

    def get_old_followers(self):
        return FollowRelationship.objects.seen(blog_id=self.id).annotate(old=F("seen"))

    def set_followers_as_old(self, followers):
        for follower in followers:
            follower.seen = True
        FollowRelationship.objects.bulk_update(followers, ["seen"])

    def save(self, *args, **kwargs):
        self.slug = unique_slugify(self, [self.title])
        super().save(*args, **kwargs)


class TaggedBlog(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.blog} tagged by {self.tag.name}"

    class Meta:
        unique_together = ("blog", "tag")


class FollowRelationship(models.Model):
    profile = models.ForeignKey(
        Profile, related_name="rel_from_set", on_delete=models.CASCADE
    )
    blog = models.ForeignKey(Blog, related_name="rel_to_set", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    seen = models.BooleanField(default=False)

    objects = FollowRelationshipManager()

    class Meta:
        ordering = ("-created",)
        unique_together = ("profile", "blog")

    def __str__(self):
        return f"{self.profile} follows {self.blog} blog"

app/blogs/forms.py
from django import forms

from tags.forms import TagField
from tags.models import Tag

from .models import Blog


class NewBlogForm(forms.ModelForm):
    tags = TagField()

    def __init__(self, *args, **kwargs):
        if "instance" in kwargs:
            initial = kwargs.get("initial", {})
            initial["tags"] = kwargs["instance"].tags.all()
            kwargs["initial"] = initial
        super().__init__(*args, **kwargs)

    def save(self, *args, author=None, commit=True, **kwargs):
        instance = super().save(*args, commit=False, **kwargs)
        if author is not None:
            instance.author = author

        if commit:
            instance.save()
            blog_tags = self.cleaned_data["tags"]
            blog_tags = Tag.tags.add(*blog_tags)
            instance.tags.set(blog_tags)

        return instance

    class Meta:
        model = Blog
        fields = ("title", "subtitle", "about", "image", "is_active")
        widgets = {
            "image": forms.ClearableFileInput(attrs={"class": "cleareable-file-input"})
        }

app/blogs/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, InvalidPage, PageNotAnInteger, Paginator
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_GET, require_POST

from .forms import NewBlogForm
from .models import Blog, FollowRelationship


def blog_list(request):
    blogs = Blog.active.all()
    return render(request, "blogs/blog/blogs-list.html", {"blogs": blogs})


def blog_ajax_list(request):
    blogs = Blog.objects.all()
    paginator = Paginator(blogs, 8)
    page = request.GET.get("page")
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        # if page is not a integer deliver the first page
        blogs = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # If the request is AJAX and the page is out of range
            # return an empty page
            return HttpResponse("")
        # If page is out of range deliver last page of results
        blogs = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, "blogs/blog/blogs-ajax-list.html", {"blogs": blogs})
    return render(request, "blogs/blog/blogs-list.html", {"blogs": blogs})


def blog_detail(request, slug):
    blog = Blog.objects.get(slug=slug)
    posts = blog.posts.filter(status="published").prefetch_related("sections")
    return render(
        request, "blogs/blog/blog-detail.html", {"blog": blog, "posts": posts}
    )


@login_required
def new_blog(request):
    if request.method == "POST":
        blog_form = NewBlogForm(data=request.POST, files=request.FILES)
        if blog_form.is_valid():
            new_blog = blog_form.save(author=request.user.profile)
            return render(request, "blogs/blog/blog-detail.html", {"blog": new_blog})
    else:
        blog_form = NewBlogForm()
    return render(request, "blogs/blog/blog-new.html", {"blog_form": blog_form})


@login_required
def edit_blog(request, slug):
    blog = get_object_or_404(Blog.objects.all(), slug=slug)
    if request.method == "POST":
        blog_form = NewBlogForm(request.POST, request.FILES, instance=blog)
        if blog_form.is_valid():
            updated_blog = blog_form.save()
            message = f"{updated_blog.title} updated succesfully"
            messages.add_message(request, messages.SUCCESS, message)
            return redirect("blogs:manage_blogs")
    else:
        blog_form = NewBlogForm(instance=blog)

    return render(request, "blogs/blog/blog-edit.html", {"blog_form": blog_form})


@login_required
def delete_blog(request, blog_id):
    blog = get_object_or_404(Blog.objects.all(), id=blog_id)
    if request.method == "DELETE":
        blog.delete()
        return JsonResponse({"status": "ok"})
    return JsonResponse({"status": "error"})


@login_required
@ensure_csrf_cookie
def manage_blogs(request):
    user_id = request.user.id
    user_blogs = Blog.objects.filter(author__user__id=user_id)
    active_blogs = user_blogs.filter(is_active=True)
    inactive_blogs = user_blogs.filter(is_active=False)
    return render(
        request,
        "blogs/blog/blogs-manage.html",
        {"active_blogs": active_blogs, "inactive_blogs": inactive_blogs},
    )


@require_POST
@login_required
def blog_follow(request):
    post_data = json.loads(request.body.decode("utf-8"))
    blog_id = post_data.get("id")
    action = post_data.get("action")
    if blog_id and action:
        try:
            blog = Blog.objects.get(id=blog_id)
            if action == "follow":
                FollowRelationship.objects.create(
                    blog=blog, profile=request.user.profile
                )
            else:
                FollowRelationship.objects.filter(
                    blog=blog, profile=request.user.profile
                ).delete()
            return JsonResponse({"status": "ok"})
        except Blog.DoesNotExist:
            return JsonResponse({"status": "error"})
    return JsonResponse({"status": "error"})


@require_GET
@login_required
def blog_followers(request, slug):
    blog = get_object_or_404(Blog.objects.all(), slug=slug)
    old_followers = blog.get_old_followers()
    new_followers = blog.get_new_followers()
    all_followers = new_followers | old_followers

    paginator = Paginator(all_followers, 15)

    is_ajax = request.headers.get("X-Requested-With") == "XMLHttpRequest"

    if is_ajax:
        page = request.GET.get("page")
        try:
            followers = list(paginator.page(page))
        except InvalidPage:
            return HttpResponse("")

        blog.set_followers_as_old(new_followers)

        return render(
            request,
            "account/profile/followers-ajax-list.html",
            {"blog": blog, "followers": followers},
        )
    else:
        try:
            followers = list(paginator.page(1))
        except EmptyPage:
            new_followers = []

    blog.set_followers_as_old(new_followers)

    return render(
        request,
        "account/profile/followers-list.html",
        {"blog": blog, "followers": followers},
    )

app/blogs/templates/blogs/blog/blog-detail.html
{% extends "blogs-base.html" %}
{% load static %}
{% load custom_tags %}
{% load custom_filters %}
{% load thumbnail %}

{% block title %}{{ blog.title }}{% endblock %}

{% block javascript %}
<script src="{% static 'js/get-cookie.js' %}" type="text/javascript" defer></script>
<script src="{% static 'js/update-followers.js' %}" type=" application/javascript" defer></script>
{% endblock %}

{% block content %}
<section class="blog-detail">
    {% if blog.image %}
        <div class="blog-image">
            <img src="{{ blog.image.url }}">
        </div>
    {% endif %}
    <div class="blog-title">
        <h2> {{ blog.title }} </h2>
        <p> {{ blog.subtitle }} </p>
    </div>

    <section class="blog-about">
    {% with total_followers=blog.followers.count %}
    <div>
        {% if request.user.id and request.user.id == blog.author.user.id %}
        <a href="{% url 'blogs:blog_followers' blog.slug %}" class="count">
            <span class="total">{{ total_followers }}</span>
            follower{{ total_followers|pluralize }}
        </a>
        {% else %}
        <span class="count">
            <span class="total">{{ total_followers }}</span>
            follower{{ total_followers|pluralize }}
        </span>
        {% endif %}
        {% if request.user.id and request.user.id != blog.author.user.id %}
        <a href="" data-id="{{ blog.id }}" data-action="{% if request.user.profile in blog.followers.all %}un{% endif %}follow" class="follow button">
            {% if request.user.profile not in blog.followers.all %}
            Follow
            {% else %}
            Unfollow
            {% endif %}
        </a>
        {% endif %}
    </div>
    {% endwith %}
    </section>

    {% if blog.about %}
        <section class="blog-about">
            <h2>About blog</h2>
            <p> {{ blog.about|html_links|linebreaks }} </p>
            {% endif %}
            {% if blog.author.about %}
        </section>
    {% endif %}

    <section class="blog-about">
        <h2> Author </h2>
        <a href="{{ blog.author.get_absolute_url }}">
            <div class="author__detail">
                <img src="{% thumbnail blog.author.photo 40x40 crop %}" class="author__avatar">
                <div>{{ blog.author.user.get_username }}</div>
            </div>
        </a>
    </section>

    <section class="blog-about">
        <h2> Tags </h2>
        {% if blog.tags.all %}
            {% for tag in blog.tags.all %}
                <span>#{{ tag.name }}</span>
            {% endfor %}
        {% else %}
            <p>No tags yet :(</p>
        {% endif %}
        </a>
    </section>

    <section class="blog-about">
        <h2>Posts</h2>
        {% if posts %}
        <div class="post-list-simple">
            {% for post in posts %}
                {% post_card post %}
            {% endfor %}
        </div>
        {% else %}
        <p>No posts yet :(</p>
        {% endif %}
    </section>

</section>
{% endblock %}

app/blogs/templates/blogs/blog/blog-edit.html
{% extends "base.html" %}

{% block title %}New blog{% endblock %}

{% block content %}
<h1>Edit blog</h1>
<form method="post" enctype="multipart/form-data">
  {{ blog_form.as_p }}
  {% csrf_token %}
  <p><input type="submit" value="Edit blog"></p>
</form>
{% endblock %}

app/blogs/templates/blogs/blog/blog-new.html
{% extends "base.html" %}

{% block title %}New blog{% endblock %}

{% block content %}
<h1>New blog</h1>
<form method="post" enctype="multipart/form-data">
  {{ blog_form.as_p }}
  {% csrf_token %}
  {{ blog_form.author }}
  <p><input type="submit" value="New blog"></p>
</form>
{% endblock %}

app/blogs/templates/blogs/blog/blogs-ajax-list.html
{% load thumbnail %}

{% for blog in blogs %}
<div class="image">
  <a href="{{ blog.get_absolute_url }}">
    {% thumbnail blog.image 140x140 crop="smart" as im %}
    <a href="{{ blog.get_absolute_url }}">
      <img src="{{ im.url }}">
    </a>
  </a>
  <div class="info">
    <a href="{{ blog.get_absolute_url }}" class="title">
      {{ blog.title }}
    </a>
  </div>
</div>
{% endfor %}

app/blogs/templates/blogs/blog/blogs-list.html
{% extends "blogs-base.html" %}
{% load static %}

{% block title %}All active blogs{% endblock %}

{% block css %}
<link href="{% static '/css/blogs.css' %}" rel="stylesheet">
<link href="{% static '/css/blog-card-detailed.css' %}" rel="stylesheet" defer>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/blog-card-detailed.js' %}" type="text/javascript" defer></script>
<script src="{% static 'js/fetch-detailed-blogs.js' %}" type="text/javascript" defer></script>
{% endblock %}

{% block content %}
<h1>All active blogs</h1>
<div class="blogs-list-detailed"></div>
{% endblock %}

app/blogs/templates/blogs/blog/blogs-manage.html
{% extends "blogs-base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}Your blogs{% endblock %}

{% block javascript %}
<script src="{% static 'js/get-cookie.js' %}" type="text/javascript" defer></script>
<script src="{% static 'js/delete-modal.js' %}" type="text/javascript" defer></script>
<script src="{% static 'js/delete-blog.js' %}" type="text/javascript" defer></script>
{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<h1>Your blogs</h1>

<section class="new-blog">
  <a href="{% url 'blogs:new_blog' %}">
    <button>
      NEW BLOG
    </button>
  </a>
</section>

<section class="section">
  <h2>Active blogs</h2>
  <div class="blog-list">
    {% if active_blogs %}
      {% for blog in active_blogs %}
        <div class="blog-card">
          <div class="blog-card__avatar">
            <a href="{{ blog.get_absolute_url }}">
              {% thumbnail blog.image 200x200 crop="smart" as im %}
              <img src="{{ im.url }}">
            </a>
          </div>
          <div class="blog-card__content">
            <div class="blog-title">
              <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>
            </div>
            <div class="blog-subtitle">
              {{ blog.subtitle }}
            </div>
            <div class="panel">
              <div class="edit-delete">
                <a href="{% url 'posts:manage_posts' blog.slug %}" class="blog-card__button">
                  <button class="write-story-btn create">
                    Stories
                  </button>
                </a>
                <a href="{% url 'posts:create_post' blog.id %}" class="blog-card__button">
                  <button class="write-story-btn create">
                    New story
                  </button>
                </a>
              </div>
                <div class="edit-delete">
                  <a href="{% url 'blogs:edit_blog' blog.slug %}" class="blog-card__button">
                    <button class="edit-blog-btn edit">
                      Edit
                    </button>
                  </a>
                  <span class="blog-card__button">
                    <button data-id="{{ blog.id }}" data-title="{{ blog.title }}" class="delete-blog-btn delete">
                      Delete
                    </button>
                  </span>
                </div>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <div>No active blogs yet :(</div>
    {% endif %}
  </div>
</section>

<section class="section last">
  <h2>Inactive blogs</h2>
  <div class="blog-list">
    {% if inactive_blogs %}
      {% for blog in inactive_blogs %}
        <div class="blog-card">
          <div class="blog-card__avatar">
            <a href="{{ blog.get_absolute_url }}">
              {% thumbnail blog.image 200x200 crop="smart" as im %}
              <img src="{{ im.url }}">
            </a>
          </div>
          <div class="blog-card__content">
            <div class="blog-title">
              <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>
            </div>
            <div class="blog-subtitle">
              {{ blog.subtitle }}
            </div>
            <div class="panel">
              <div class="edit-delete">
                <a href="{% url 'posts:manage_posts' blog.slug %}" class="blog-card__button">
                  <button class="write-story-btn create">
                    Stories
                  </button>
                </a>
                <a href="{% url 'posts:create_post' blog.id %}" class="blog-card__button">
                  <button class="write-story-btn create">
                    New story
                  </button>
                </a>
              </div>
              <div class="edit-delete">
                <a href="{% url 'blogs:edit_blog' blog.slug %}" class="blog-card__button">
                  <button class="edit-blog-btn edit">
                    Edit
                  </button>
                </a>
                <span class="blog-card__button">
                  <button data-id="{{ blog.id }}" data-title="{{ blog.title }}" class="delete-blog-btn delete">
                    Delete
                  </button>
                </span>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <div>No inactive blogs at the moment :)</div>
    {% endif %}
  </div>
</section>

<delete-modal 
  url="http://localhost:8000/blogs/delete/" 
  data-object="blog">
</delete-modal>

{% endblock %}