app/blogs/urls.py
from django.urls import path

from . import api, views

app_name = "blogs"

urlpatterns = [
    # post views
    path("", views.blog_ajax_list, name="blog_list"),
    path("new/", views.new_blog, name="new_blog"),
    path("edit/<slug:slug>", views.edit_blog, name="edit_blog"),
    path("delete/<int:blog_id>", views.delete_blog, name="delete_blog"),
    path("manage/", views.manage_blogs, name="manage_blogs"),
    path("follow/", views.blog_follow, name="blog_follow"),
    path("<slug:slug>/followers", views.blog_followers, name="blog_followers"),
    path("<slug:slug>/", views.blog_detail, name="blog_detail"),
    path("detailed", api.get_detailed_blogs, name="blog_detailed"),
]

app/posts/urls.py
from django.urls import path

from . import api, views

app_name = "posts"

urlpatterns = [
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("post/<int:blog_id>/create/", views.create_post, name="create_post"),
    path("post/<slug:post_slug>/edit/", views.edit_post, name="edit_post"),
    path("delete/<int:post_id>", views.delete_post, name="delete_post"),
    path("manage/<slug:blog_slug>", views.manage_posts, name="manage_posts"),
    path("", views.post_list, name="post_list"),
    path("detailed/", api.get_detailed_posts, name="post_detailed"),
]

app/publishing_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("blogs/", include("blogs.urls", namespace="blogs")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("search/", include("search.urls", namespace="search")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/posts/forms.py
from django import forms
from django.forms import formset_factory

from tags.forms import TagField

from .models import Citation, Image, Post, SubTitle, Text


class PostForm(forms.ModelForm):
    tags = TagField(required=False)

    def __init__(self, *args, **kwargs):
        if "instance" in kwargs:
            initial = kwargs.get("initial", {})
            initial["tags"] = kwargs["instance"].tags.all()
            kwargs["initial"] = initial
        super().__init__(*args, **kwargs)

    class Meta:
        model = Post
        fields = ("status",)


class TitleForm(forms.Form):
    order = forms.IntegerField(min_value=0, widget=forms.HiddenInput())
    title = forms.CharField(
        label="Title",
        widget=forms.Textarea(
            attrs={
                "class": "form-story-title",
                "placeholder": "Story title",
                "autocomplete": "off",
                "rows": 1,
            }
        ),
    )


class SubTitleForm(forms.ModelForm):
    order = forms.IntegerField(min_value=0, widget=forms.HiddenInput())

    class Meta:
        model = SubTitle
        fields = ("subtitle",)
        widgets = {
            "subtitle": forms.Textarea(
                attrs={
                    "class": "form-story-subtitle",
                    "placeholder": "Subtitle",
                    "autocomplete": "off",
                    "rows": 1,
                }
            )
        }


SubTitleFormset = formset_factory(SubTitleForm, extra=0)


class TextForm(forms.ModelForm):
    order = forms.IntegerField(min_value=0, widget=forms.HiddenInput())

    class Meta:
        model = Text
        fields = ("text",)
        widgets = {
            "text": forms.Textarea(
                attrs={
                    "class": "form-story-text",
                    "placeholder": "Text",
                    "autocomplete": "off",
                    "rows": 1,
                }
            )
        }

    def save(self, commit=True):
        return super(Text, self).save(commit=commit)


TextFormset = formset_factory(TextForm, extra=0)


class CitationForm(forms.ModelForm):
    order = forms.IntegerField(min_value=0, widget=forms.HiddenInput())

    class Meta:
        model = Citation
        fields = ("citation",)
        widgets = {
            "citation": forms.Textarea(
                attrs={
                    "class": "form-story-citation",
                    "placeholder": "Citation",
                    "autocomplete": "off",
                    "rows": 1,
                }
            )
        }


CitationFormset = formset_factory(CitationForm, extra=0)


class ImageForm(forms.ModelForm):
    order = forms.IntegerField(min_value=0, widget=forms.HiddenInput())

    class Meta:
        model = Image
        fields = ("file",)
        required = ("file",)


ImageFormset = formset_factory(ImageForm, extra=0)

app/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.db import transaction
from django.db.utils import IntegrityError
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse
from django.views.decorators.csrf import ensure_csrf_cookie

from blogs.models import Blog
from common.utils import unique_slugify
from tags.models import Tag

from .forms import (
    CitationFormset,
    ImageFormset,
    PostForm,
    SubTitleFormset,
    TextFormset,
    TitleForm,
)
from .models import Citation, Image, Post, Section, SubTitle, Text, Title


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(
        Post.objects.prefetch_related("sections").all(),
        slug=slug,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    return render(request, "posts/post/post-detail.html", {"post": post})


def post_list(request):
    return render(request, "posts/post/posts-list.html", {})


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post.objects.all(), id=post_id)
    if request.method == "DELETE":
        post.delete()
        return JsonResponse({"status": "ok"})
    return JsonResponse({"status": "error"})


@login_required
@ensure_csrf_cookie
def manage_posts(request, blog_slug):
    blog = get_object_or_404(Blog.objects.all(), slug=blog_slug)
    published_posts = blog.posts.filter(status="published")
    draft_posts = blog.posts.filter(status="draft")
    return render(
        request,
        "posts/post/posts-manage.html",
        {"blog": blog, "published_posts": published_posts, "draft_posts": draft_posts},
    )


SUBTITLE_PREFIX = "subtitle"
TEXT_PREFIX = "text"
CITATION_PREFIX = "citation"
IMAGE_PREFIX = "image"


@login_required
def edit_post(request, post_slug):
    post = get_object_or_404(Post.objects.all(), slug=post_slug)
    blog = post.blog

    if request.method == "GET":
        post_form = PostForm(instance=post)
        title_form = TitleForm(data=post.get_title_section())
        subtitle_formset = SubTitleFormset(
            initial=post.get_subtitle_sections(), prefix=SUBTITLE_PREFIX
        )
        text_formset = TextFormset(initial=post.get_text_sections(), prefix=TEXT_PREFIX)
        citation_formset = CitationFormset(
            initial=post.get_citation_sections(), prefix=CITATION_PREFIX
        )
        image_formset = ImageFormset(
            initial=post.get_image_sections(),
            prefix=IMAGE_PREFIX,
        )
    elif request.method == "POST":

        post_form = PostForm(request.POST)
        title_form = TitleForm(request.POST)
        subtitle_formset = SubTitleFormset(request.POST or None, prefix=SUBTITLE_PREFIX)
        text_formset = TextFormset(request.POST or None, prefix=TEXT_PREFIX)
        citation_formset = CitationFormset(request.POST or None, prefix=CITATION_PREFIX)
        image_formset = ImageFormset(
            data=request.POST or None, files=request.FILES or None, prefix=IMAGE_PREFIX
        )

        if (
            post_form.is_valid()
            and title_form.is_valid()
            and subtitle_formset.is_valid()
            and text_formset.is_valid()
            and citation_formset.is_valid()
        ):

            post_cd = post_form.cleaned_data
            post_status = post_cd["status"]
            post_tags = post_cd["tags"]
            new_story = post
            new_story.status = post_status
            sections = []

            #########
            # TITLE #
            #########
            title_cd = title_form.cleaned_data
            title = title_cd["title"]
            title_order = title_cd["order"]
            title_object = Title(title=title)

            sections.append({"content_object": title_object, "order": title_order})

            new_slug = unique_slugify(new_story, [title])
            new_story.slug = new_slug

            #############
            # SUBTITLES #
            #############
            subtitle_objects = []
            for subtitle_form in subtitle_formset:
                subtitle_cd = subtitle_form.cleaned_data
                if subtitle_cd:
                    subtitle = subtitle_cd["subtitle"]
                    subtitle_order = subtitle_cd["order"]
                    subtitle_object = SubTitle(subtitle=subtitle)
                    subtitle_objects.append(subtitle_object)
                    sections.append(
                        {"content_object": subtitle_object, "order": subtitle_order}
                    )

            text_objects = []
            for text_form in text_formset:
                text_cd = text_form.cleaned_data
                text = text_cd["text"]
                text_order = text_cd["order"]
                text_object = Text(text=text)

                text_objects.append(text_object)
                sections.append({"content_object": text_object, "order": text_order})

            citation_objects = []
            for citation_form in citation_formset:
                citation_cd = citation_form.cleaned_data
                if citation_cd:
                    citation = citation_cd["citation"]
                    citation_order = citation_cd["order"]
                    citation_object = Citation(citation=citation)

                    citation_objects.append(citation_object)
                    sections.append(
                        {"content_object": citation_object, "order": citation_order}
                    )

            image_objects = []
            if image_formset.is_valid():
                image_objects = []
                for image_form in image_formset:
                    image_cd = image_form.cleaned_data
                    if image_cd:
                        file = image_cd["file"]
                        file_order = image_cd["order"]
                        file_object = Image(file=file)

                        image_objects.append(file_object)
                        sections.append(
                            {"content_object": file_object, "order": file_order}
                        )

            try:
                with transaction.atomic():
                    post_tags = Tag.tags.add(*post_tags)
                    new_story.save()
                    if post_tags:
                        new_story.tags.set(post_tags)
                    else:
                        new_story.tags.all().delete()
                    title_object.save()
                    if len(subtitle_objects):
                        SubTitle.objects.bulk_create(subtitle_objects)
                    if len(text_objects):
                        Text.objects.bulk_create(text_objects)
                    if len(citation_objects):
                        Citation.objects.bulk_create(citation_objects)
                    if len(image_objects):
                        Image.objects.bulk_create(image_objects)
                    if len(sections):

                        def create_section(args_dict):
                            return Section(post=new_story, **args_dict)

                        if image_objects:
                            new_story.sections.all().delete()
                        else:
                            image_id = ContentType.objects.get_for_model(Image).id
                            new_story.sections.exclude(content_type=image_id).delete()
                        sections = map(create_section, sections)
                        Section.objects.bulk_create(sections)
            except IntegrityError as e:
                print("Integrity error!", e)

                return render(
                    request,
                    "posts/post/edit-story.html",
                    {
                        "blog": blog,
                        "post_form": post_form,
                        "title_form": title_form,
                        "subtitle_formset": subtitle_formset,
                        "text_formset": text_formset,
                        "citation_formset": citation_formset,
                        "image_formset": image_formset,
                    },
                )

            return redirect(reverse("posts:manage_posts", args=[blog.slug]))

    return render(
        request,
        "posts/post/edit-story.html",
        {
            "post": post,
            "blog": blog,
            "post_form": post_form,
            "title_form": title_form,
            "subtitle_formset": subtitle_formset,
            "text_formset": text_formset,
            "citation_formset": citation_formset,
            "image_formset": image_formset,
        },
    )


def create_post(request, blog_id):
    blog = get_object_or_404(Blog.objects.all(), pk=blog_id)

    if request.method == "GET":
        post_form = PostForm()
        title_form = TitleForm()
        subtitle_formset = SubTitleFormset(prefix=SUBTITLE_PREFIX)
        text_formset = TextFormset(prefix=TEXT_PREFIX)
        citation_formset = CitationFormset(prefix=CITATION_PREFIX)
        image_formset = ImageFormset(prefix=IMAGE_PREFIX)
    elif request.method == "POST":
        post_form = PostForm(request.POST)
        title_form = TitleForm(request.POST)
        subtitle_formset = SubTitleFormset(request.POST or None, prefix=SUBTITLE_PREFIX)
        text_formset = TextFormset(request.POST or None, prefix=TEXT_PREFIX)
        citation_formset = CitationFormset(request.POST or None, prefix=CITATION_PREFIX)
        image_formset = ImageFormset(
            data=request.POST or None, files=request.FILES or None, prefix=IMAGE_PREFIX
        )

        if (
            post_form.is_valid()
            and title_form.is_valid()
            and subtitle_formset.is_valid()
            and text_formset.is_valid()
            and image_formset.is_valid()
            and citation_formset.is_valid()
        ):

app/posts/templates/posts/post/edit-story.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link href="{% static '/css/write-story.css' %}" rel="stylesheet" defer>
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'js/drag-and-drop.js' %}" defer></script>
<script type="text/javascript" src="{% static 'js/write-story.js' %}" defer></script>
{% endblock %}

{% block title %}
Blog {{ blog.title }} by {{ blog.author }}
{% endblock %}

{% block content %}
<h1>Blog "{{ blog.title }}" by {{ blog.author }}</h1>
<section class="write-story">
  {{ post}}
  <form id="story-form" action="{% url 'posts:edit_post' post.slug %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ subtitle_formset.management_form }}
    {{ text_formset.management_form }}
    {{ citation_formset.management_form }}
    {{ image_formset.management_form }}

    <hr>
    <div class="post-form">
      {{ post_form }}
    </div>
    <hr>

    <div class="write-story__header">
      <h2 class="header">Edit your new story below and submit when ready</h2>
      <input id="submit-story" type="submit" value="Edit story" class="create">
    </div>

    <div>
      <hr>
    </div>

    <div class="story-content">

      <div class="story-content__item title_" style="display:none">
        <div class="item__wrapper">
          {{ title_form.title }}
          {{ title_form.order }}
        </div>
      </div>

      {% for form in subtitle_formset %}
        <div class="story-content__item subtitle_" style="display:none">
          <div class="item__wrapper">
            {{ form.subtitle }}
            {{ form.order }}
          </div>
        </div>
      {% endfor %}
      
      {% for form in text_formset %}
        <div class="story-content__item text_" style="display:none">
          <div class="item__wrapper">
            {{ form.text }}
            {{ form.order }}
          </div>
        </div>
      {% endfor %}

      {% for form in citation_formset %}
      <div class="story-content__item citation_" style="display:none">
        <div class="item__wrapper">
          {{ form.citation }}
          {{ form.order }}
        </div>
      </div>
      {% endfor %}


      {% for form in image_formset %}
      <div class="story-content__item image_" style="display:none">
        <div class="item__wrapper">
          {{ form.file }}
          {{ form.order }}
          <div class="img-wrapper">
            <img id="id_image-__prefix__-src">
          </div>
        </div>
      </div>
      {% endfor %}

    </div>

    <div id="empty-subtitle-form" style="display:none">
      {{ subtitle_formset.empty_form.subtitle }}
      {{ subtitle_formset.empty_form.order }}
    </div>

    <div id="empty-text-form" style="display:none">
      {{ text_formset.empty_form.text }}
      {{ text_formset.empty_form.order }}
    </div>

    <div id="empty-citation-form" style="display:none">
      {{ citation_formset.empty_form.citation }}
      {{ citation_formset.empty_form.order }}
    </div>

    <div id="empty-image-form" style="display:none">
      {{ image_formset.empty_form.file }}
      {{ image_formset.empty_form.order }}
      <div class="img-wrapper">
        <img id="id_image-__prefix__-src">
      </div>
    </div>
  </form>

  <div>
    <hr>
  </div>

  <section class="content-types">
    <h3>Add new section:</h3>
    <div class="content-types__menu">
      <input type="button" value="Subtitle" id="add-subtitle" />
      <input type="button" value="Text" id="add-text" />
      <input type="button" value="Image" id="add-img" />
      <input type="button" value="Citation" id="add-citation" />
    </div>
  </section>

  <div>
    <hr>
  </div>

</section>
{% endblock %}

app/posts/templates/posts/post/post-detail.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link href="{% static '/css/write-story.css' %}" rel="stylesheet" defer>
<link href="{% static '/css/display-story.css' %}" rel="stylesheet" defer>
<link href="{% static '/css/post-card-detailed.css' %}" rel="stylesheet" defer>
{% endblock %}

{% block javascript %}
{{ post.slug|json_script:"post-data" }}
<script src="{% static 'js/post-card-detailed.js' %}" type="text/javascript" defer></script>
<script src="{% static 'js/find-similar-posts.js' %}" type="text/javascript" defer></script>
{% endblock %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<div class="story-sections">
    {% for section in post.sections.all %}
        {% render_section section %}
        {% if section.content_object.title %}
            <div class="post-card__avatar author-image bigger margin-bottom">
                <a href="{{ post.blog.author.get_absolute_url }}">
                    <img src="{{ post.blog.author.photo.url }}">
                </a>
                <div>
                    <div class="info bigger">
                        By <a href="{{ post.blog.author.get_absolute_url }}">
                            {{ post.blog.author.user.username }} </a>
                    </div>
                    <div class="post-published bigger">
                        {{ post.publish|date }}
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>

<hr>
<div class="similar">
    <button class="find-similar-posts">Find similar posts</button>
</div>
<hr>

{% endblock %}

app/posts/templates/posts/post/posts-list.html
{% extends "posts-base.html" %}
{% load static %}

{% block title %}All published posts{% endblock %}

{% block css %}
<link href="{% static '/css/write-story.css' %}" rel="stylesheet" defer>
<link href="{% static '/css/display-story.css' %}" rel="stylesheet" defer>
<link href="{% static '/css/post-card-detailed.css' %}" rel="stylesheet" defer>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/post-card-detailed.js' %}" type="text/javascript" defer></script>
<script src="{% static 'js/fetch-detailed-posts.js' %}" type="text/javascript" defer></script>
{% endblock %}

{% block content %}
<h1>All published posts</h1>
<div class="posts-list similar"></div>
{% endblock %}

app/posts/templates/posts/post/posts-manage.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %} {{ blog.title }} posts {% endblock %}

{% block css %}
<link href="{% static '/css/post-card-manage.css' %}" rel="stylesheet" defer>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/get-cookie.js' %}" type="text/javascript" defer></script>
<script src="{% static 'js/delete-modal.js' %}" type="text/javascript" defer></script>
<script src="{% static 'js/delete-post.js' %}" type="text/javascript" defer></script>
{% endblock %}


{% block content %}

{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<h1>Your stories on "{{ blog.title }}"</h1>

<section class="new-post">
  <a href="{% url 'posts:create_post' blog.id %}">
    <button>
      New story
    </button>
  </a>
</section>

<section class="section">
  <h2>Published stories</h2>
  <div class="post-list">
    {% if published_posts %}
    {% for post in published_posts %}
    <div class="post-card-manage">
      <div class="post-card-manage__avatar">
        <a href="{{ post.get_absolute_url }}">
          {% thumbnail post.first_image 100x100 crop="smart" as im %}
          <img src="{{ im.url }}">
        </a>
      </div>
      <div class="post-card-manage__content">
        <div class="post-card-manage__title">
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </div>
        <div class="panel">
          <div class="edit-delete">
            <a href="{% url 'posts:edit_post' post.slug %}" class="post-card__button">
              <button class="edit-post-btn edit">
                Edit
              </button>
            </a>
            <span class="post-card__button">
              <button data-id="{{ post.id }}" data-title="{{ post.title }}" class="delete-post-btn delete">
                Delete
              </button>
            </span>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div>No published stories yet :(</div>
    {% endif %}
  </div>
</section>

<section class="section last">
  <h2>Draft stories</h2>
  <div class="post-manage-list">
    {% if draft_posts %}
    {% for post in draft_posts %}
    <div class="post-card-manage">
      <div class="post-card-manage__avatar">
        <a href="{{ post.get_absolute_url }}">
          {% thumbnail post.first_image 100x100 crop="smart" as im %}
          <img src="{{ im.url }}">
        </a>
      </div>
      <div class="post-card-manage__content">
        <div class="post-card-manage__title">
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </div>
        <div class="panel">
          <div class="edit-delete">
            <a href="{% url 'posts:edit_post' post.slug %}" class="post-card__button"><button class="edit-post-btn edit">Edit</button></a>
            <span class="blog-card__button">
              <button data-id="{{ post.id }}" data-title="{{ post.title }}" class="delete-post-btn delete">
                Delete
              </button>
            </span>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div>No draft stories at the moment :)</div>
    {% endif %}
  </div>
</section>

<delete-modal 
  url="http://localhost:8000/posts/delete/"
  data-object="post"
></delete-modal>

{% endblock %}

app/posts/templates/posts/post/sections-list.html
{% extends "post_base.html" %}
{% load post %}

{% block title %}
Post {{ post.title }}
{% endblock %}

{% block content %}
<div class="module">
  <h2>Post {{ post.order|add:1 }}: {{ post.title }}</h2>
  <h3>Post sections:</h3>
  <div id="module-contents">
    {% for section in post.sections.all %}
    <div data-id="{{ section.id }}">
      {% with item=section.item %}
      <p>{{ item }} ({{ item|model_name }})</p>
      <a href="{% url 'posts:post_section_update' post.id item|model_name item.id %}">
        Edit
      </a>
      <form action="{% url 'posts:post_section_delete' section.id %}" method="post">
        <input type="submit" value="Delete">
        {% csrf_token %}
      </form>
      {% endwith %}
    </div>
    {% empty %}
    <p>This post has no sections yet.</p>
    {% endfor %}
  </div>
  <h3>Add new section:</h3>
  <ul class="content-types">
    <li><a href="{% url 'posts:post_section_create' post.id 'text' %}">
        Text</a></li>
    <li><a href="{% url 'posts:post_section_create' post.id 'image' %}">
        Image</a></li>
    <li><a href="{% url 'posts:post_section_create' post.id 'video' %}">
        Video</a></li>
  </ul>
</div>
{% endblock %}

app/posts/templates/posts/post/write-story.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link href="{% static '/css/write-story.css' %}" rel="stylesheet" defer>
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'js/drag-and-drop.js' %}" defer></script>
<script type="text/javascript" src="{% static 'js/write-story.js' %}" defer></script>
{% endblock %}

{% block title %}
Blog {{ blog.title }} by {{ blog.author }}
{% endblock %}

{% block content %}
<h1>Blog "{{ blog.title }}" by {{ blog.author }}</h1>
<section class="write-story">
  <form id="story-form" action="{% url 'posts:create_post' blog.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ subtitle_formset.management_form }}
    {{ text_formset.management_form }}
    {{ citation_formset.management_form }}
    {{ image_formset.management_form }}

    <hr>
    <div class="post-form">
      {{ post_form }}
    </div>
    <hr>

    <div class="write-story__header">
      <h2 class="header">Write your new story below and submit when ready</h2>
      <input id="submit-story" type="submit" value="Create story" class="create">
    </div>

    <div>
      <hr>
    </div>

    <div class="story-content">

      <div class="story-content__item">
        <div class="item__wrapper">
          {{ title_form.title }}
          {{ title_form.order }}
        </div>
      </div>
    </div>

    <div id="empty-subtitle-form" style="display:none">
      {{ subtitle_formset.empty_form.subtitle }}
      {{ subtitle_formset.empty_form.order }}
    </div>

    <div id="empty-text-form" style="display:none">
      {{ text_formset.empty_form.text }}
      {{ text_formset.empty_form.order }}
    </div>

    <div id="empty-citation-form" style="display:none">
      {{ citation_formset.empty_form.citation }}
      {{ citation_formset.empty_form.order }}
    </div>

    <div id="empty-image-form" style="display:none">
      {{ image_formset.empty_form.file }}
      {{ image_formset.empty_form.order }}
      <div class="img-wrapper">
        <img id="id_image-__prefix__-src">
      </div>
    </div>
  </form>

  <div>
    <hr>
  </div>

  <section class="content-types">
    <h3>Add new section:</h3>
    <div class="content-types__menu">
      <input type="button" value="Subtitle" id="add-subtitle" />
      <input type="button" value="Text" id="add-text" />
      <input type="button" value="Image" id="add-img" />
      <input type="button" value="Citation" id="add-citation" />
    </div>
  </section>

  <div>
    <hr>
  </div>
  
</section>
{% endblock %}