app/blogs/urls.py
from django.urls import path

from . import api, views

app_name = "blogs"

urlpatterns = [
    # post views
    path("", views.blog_ajax_list, name="blog_list"),
    path("new/", views.new_blog, name="new_blog"),
    path("edit/<slug:slug>", views.edit_blog, name="edit_blog"),
    path("delete/<int:blog_id>", views.delete_blog, name="delete_blog"),
    path("manage/", views.manage_blogs, name="manage_blogs"),
    path("follow/", views.blog_follow, name="blog_follow"),
    path("<slug:slug>/followers", views.blog_followers, name="blog_followers"),
    path("<slug:slug>/", views.blog_detail, name="blog_detail"),
    path("detailed", api.get_detailed_blogs, name="blog_detailed"),
]

app/posts/urls.py
from django.urls import path

from . import api, views

app_name = "posts"

urlpatterns = [
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("post/<int:blog_id>/create/", views.create_post, name="create_post"),
    path("post/<slug:post_slug>/edit/", views.edit_post, name="edit_post"),
    path("delete/<int:post_id>", views.delete_post, name="delete_post"),
    path("manage/<slug:blog_slug>", views.manage_posts, name="manage_posts"),
    path("", views.post_list, name="post_list"),
    path("detailed/", api.get_detailed_posts, name="post_detailed"),
]

app/publishing_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("blogs/", include("blogs.urls", namespace="blogs")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("search/", include("search.urls", namespace="search")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/search/urls.py
from django.urls import path

from . import api, views

app_name = "search"

urlpatterns = [
    path("", views.search_blogs_and_posts, name="search_blogs_and_posts"),
    path("posts/similar", api.get_most_similar_posts, name="most_similar_posts"),
]

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>{% block title %}Publishing platform{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{% static '/css/base.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
    <script src="{% static 'js/menu-popup.js' %}" defer></script>
    {% block javascript %}{% endblock %}
</head>

<body>
    {% block header %}
    <header class="main-header">
        <div class="nav">
            <div class="logo-wrapper"><a href="{% url 'index' %}"><img src="{% static '/img/logo.png' %}" alt="logo" /></a></div>
            {% if request.user.is_authenticated and request.user.profile.get_new_followers_count > 0 %}
            <a href="{% url 'user_followers' %}"><p>{{ request.user.profile.get_new_followers_count }} new follower{{ request.user.profile.get_new_followers_count|pluralize }}</p></a>
            {% endif %}
            <a href="{% url 'search:search_blogs_and_posts' %}" class="move-right"><p>Search</p></a>
            <a href="{% url 'blogs:blog_list' %}"><p>Blogs</p></a>
            <a href="{% url 'posts:post_list' %}"><p>Posts</p></a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'dashboard' %}"><p>Dashboard</p></a>
            {% endif %}
            <div class="user">
                {% if request.user.is_authenticated %}
                <div class="hero-wrapper"><img id="hero" src="{{ request.user.profile.photo.url }}" alt="hero" /></div>
                {% else %}
                <a href="{% url 'login' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </header>
    {% endblock %}

    <main id="content">
        {% block content %}
        {% endblock %}
    </main>

    <div id="menu-popup" class="fade">
        <ul class="menu-list">
            <li>
                <div>
                    <a href="{{ request.user.profile.get_absolute_url }}">Your profile</a>
                </div>
            </li>
            <li>
                <div><a href="{% url 'blogs:manage_blogs' %}">Manage your blogs</a></div>
            </li>
            <li>
                <div><a href="{% url 'edit' %}">Manage your profile</a></div>
            </li>
            <li>
                <div><a href="{% url 'password_change' %}">Password change</a></div>
            </li>
            <li>
                <div><a href="{% url 'password_reset' %}">Password reset</a></div>
            </li>
            <li>
                <div><a href="{% url 'logout' %}">Sign out</a></div>
            </li>
        </ul>
    </div>
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}Welcome!{% endblock %}

{% block content %}
<h2>Welcome to my publishing platform</h2>
<section>
  <p>
    It's a place where you can find blogs and posts created by various people. <br>
    If you register you can also create your own blogs and publish on them.
  </p>
  <p>
    You can search blogs and posts by titles and/or tags. <br>
    You can also follow different blogs, and look them up on your dashboard.
    There you will find newest posts published by blogs you follow.
  </p>
  <p>
    There is whole panel dedicated to managing your blogs, posts and account.
    Main part consists of convinient way to write new posts. Each post consists of
    sections (title, subtitles, paragraphs, citations, images) which you can easly add,
    modify and also change their ordering by drop and down functionality.
    If you are logged-in, you can find it by clicking your icon on the left corner.
    Menu will show up.
  </p>
  <p>
    Under each post there is a button to search for similar posts to help you explore topics you are interested in.
  </p>
  <p>
    You can also view people who followed one of your blogs, and how long ago they did it.
    Additionaly info about new followers will be displayed on the top of the page to the left of the horse icon
  </p>
</section>
{% endblock %}